### ISSUE TITLE
Would benefit from a bit more information on the methodology

### ISSUE THREAD

**Issue by Ninjars** [cyberscribe/d20datascience#1]
I enjoyed reading this, but came away with a lot of questions.

Given the variety of capabilities of a high-level wizard, how did you work out their damage output? Was consideration given to damage avoidance abilities for either class?

The obvious challenge to your conclusion is that the simulation simplification of trading blows in direct combat is not how a wizard would be played, and that your methodology is strongly biased towards the fighter. How would the graphs change if the wizard was able to have multiple rounds in which they were able to prevent their opponent from attacking, for instance?

You could explore a sequence of scenarios, remaining at an abstract level, exploring thresholds around inflicting disadvantage or complete disabling on opponents and the trade-off of such status affecting spells vs pure damage-dealing.

How many uncontested attack rounds would the wizard party need to exceed the fighter's power curve?
Is there a point at which a threat requires too many disabling spells and so doesn't leave enough for offensive spells?
Does the use of evasion spells such as misty step provide enough benefit to offset the lack of damage being dealt that round from that party member?
If the monster is polymorphed into something harmless (ie completely disabled for an arbitrary duration) when a party member is on low health to allow a few rounds of healing and preparation, is that a good use of spell slots overall or statistically should the party soak up the casualty in order to be victorious?

**Comment by cyberscribe** [comment]
"Wizard" in this context should really be read as a label for "least powerful melee combatant". Clearly, simulating all spells in the SRD is beyond the scope of this (possibly any reasonably-sized?) project.
